"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "esv-sdk"
__version__: str = "0.3.0"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.597.9"
__user_agent__: str = "speakeasy-sdk/python 0.3.0 2.597.9 1.0.0 esv-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
