workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Esv-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/walker/esv/esv-org-api:main
        registry:
            location: registry.speakeasyapi.dev/walker/esv/esv-oas
targets:
    esv:
        target: python
        source: Esv-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/walker/esv/esv-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
