"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .esverror import EsvError
from typing import Any, TYPE_CHECKING

from esv_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError
    from .error import Error, ErrorData
    from .getpassageaudioop import (
        GetPassageAudioRequest,
        GetPassageAudioRequestTypedDict,
    )
    from .getpassagehtmlop import GetPassageHTMLRequest, GetPassageHTMLRequestTypedDict
    from .getpassagetextop import (
        GetPassageTextRequest,
        GetPassageTextRequestTypedDict,
        IndentUsing,
    )
    from .no_response_error import NoResponseError
    from .passagemeta import PassageMeta, PassageMetaTypedDict
    from .passageresponse import PassageResponse, PassageResponseTypedDict
    from .responsevalidationerror import ResponseValidationError
    from .searchpassagesop import (
        Results,
        ResultsTypedDict,
        SearchPassagesRequest,
        SearchPassagesRequestTypedDict,
        SearchPassagesResponse,
        SearchPassagesResponseBody,
        SearchPassagesResponseBodyTypedDict,
        SearchPassagesResponseTypedDict,
        Verses,
        VersesTypedDict,
    )
    from .security import Security, SecurityTypedDict

__all__ = [
    "APIError",
    "Error",
    "ErrorData",
    "EsvError",
    "GetPassageAudioRequest",
    "GetPassageAudioRequestTypedDict",
    "GetPassageHTMLRequest",
    "GetPassageHTMLRequestTypedDict",
    "GetPassageTextRequest",
    "GetPassageTextRequestTypedDict",
    "IndentUsing",
    "NoResponseError",
    "PassageMeta",
    "PassageMetaTypedDict",
    "PassageResponse",
    "PassageResponseTypedDict",
    "ResponseValidationError",
    "Results",
    "ResultsTypedDict",
    "SearchPassagesRequest",
    "SearchPassagesRequestTypedDict",
    "SearchPassagesResponse",
    "SearchPassagesResponseBody",
    "SearchPassagesResponseBodyTypedDict",
    "SearchPassagesResponseTypedDict",
    "Security",
    "SecurityTypedDict",
    "Verses",
    "VersesTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "Error": ".error",
    "ErrorData": ".error",
    "GetPassageAudioRequest": ".getpassageaudioop",
    "GetPassageAudioRequestTypedDict": ".getpassageaudioop",
    "GetPassageHTMLRequest": ".getpassagehtmlop",
    "GetPassageHTMLRequestTypedDict": ".getpassagehtmlop",
    "GetPassageTextRequest": ".getpassagetextop",
    "GetPassageTextRequestTypedDict": ".getpassagetextop",
    "IndentUsing": ".getpassagetextop",
    "NoResponseError": ".no_response_error",
    "PassageMeta": ".passagemeta",
    "PassageMetaTypedDict": ".passagemeta",
    "PassageResponse": ".passageresponse",
    "PassageResponseTypedDict": ".passageresponse",
    "ResponseValidationError": ".responsevalidationerror",
    "Results": ".searchpassagesop",
    "ResultsTypedDict": ".searchpassagesop",
    "SearchPassagesRequest": ".searchpassagesop",
    "SearchPassagesRequestTypedDict": ".searchpassagesop",
    "SearchPassagesResponse": ".searchpassagesop",
    "SearchPassagesResponseBody": ".searchpassagesop",
    "SearchPassagesResponseBodyTypedDict": ".searchpassagesop",
    "SearchPassagesResponseTypedDict": ".searchpassagesop",
    "Verses": ".searchpassagesop",
    "VersesTypedDict": ".searchpassagesop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
