"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from esv_sdk.models import EsvError
from esv_sdk.types import BaseModel
import httpx
from typing import Any, Dict, Optional


class ErrorData(BaseModel):
    code: str

    message: str

    details: Optional[Dict[str, Any]] = None


@dataclass(unsafe_hash=True)
class Error(EsvError):
    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
