"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from esv_sdk import utils
from esv_sdk.types import BaseModel
from typing import Any, Dict, Optional


class ErrorData(BaseModel):
    code: str

    message: str

    details: Optional[Dict[str, Any]] = None


class Error(Exception):
    data: ErrorData

    def __init__(self, data: ErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ErrorData)
