"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from esv_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PassageMetaTypedDict(TypedDict):
    canonical: NotRequired[str]
    chapter_start: NotRequired[List[int]]
    chapter_end: NotRequired[List[int]]
    prev_verse: NotRequired[int]
    next_verse: NotRequired[int]
    prev_chapter: NotRequired[List[int]]
    next_chapter: NotRequired[List[int]]


class PassageMeta(BaseModel):
    canonical: Optional[str] = None

    chapter_start: Optional[List[int]] = None

    chapter_end: Optional[List[int]] = None

    prev_verse: Optional[int] = None

    next_verse: Optional[int] = None

    prev_chapter: Optional[List[int]] = None

    next_chapter: Optional[List[int]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "canonical",
                "chapter_start",
                "chapter_end",
                "prev_verse",
                "next_verse",
                "prev_chapter",
                "next_chapter",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
