"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from esv_sdk.types import BaseModel, UNSET_SENTINEL
from esv_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Callable, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchPassagesRequestTypedDict(TypedDict):
    query: str
    r"""The text to search for"""
    page_size: NotRequired[int]
    r"""Number of results to return per page"""
    page: NotRequired[int]
    r"""Page number to return"""


class SearchPassagesRequest(BaseModel):
    query: Annotated[
        str,
        pydantic.Field(alias="q"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The text to search for"""

    page_size: Annotated[
        Optional[int],
        pydantic.Field(alias="page-size"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20
    r"""Number of results to return per page"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number to return"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page-size", "page"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VersesTypedDict(TypedDict):
    verse: NotRequired[str]
    r"""Verse reference"""
    text: NotRequired[str]
    r"""Verse text"""


class Verses(BaseModel):
    verse: Optional[str] = None
    r"""Verse reference"""

    text: Optional[str] = None
    r"""Verse text"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["verse", "text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResultsTypedDict(TypedDict):
    reference: NotRequired[str]
    r"""The passage reference"""
    content: NotRequired[str]
    r"""The matching passage content"""
    verses: NotRequired[List[VersesTypedDict]]


class Results(BaseModel):
    reference: Optional[str] = None
    r"""The passage reference"""

    content: Optional[str] = None
    r"""The matching passage content"""

    verses: Optional[List[Verses]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reference", "content", "verses"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SearchPassagesResponseBodyTypedDict(TypedDict):
    r"""Successful response"""

    page: NotRequired[int]
    r"""Current page number"""
    total_pages: NotRequired[int]
    r"""Total number of pages"""
    total_results: NotRequired[int]
    r"""Total number of results"""
    results: NotRequired[List[ResultsTypedDict]]


class SearchPassagesResponseBody(BaseModel):
    r"""Successful response"""

    page: Optional[int] = None
    r"""Current page number"""

    total_pages: Optional[int] = None
    r"""Total number of pages"""

    total_results: Optional[int] = None
    r"""Total number of results"""

    results: Optional[List[Results]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "total_pages", "total_results", "results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SearchPassagesResponseTypedDict(TypedDict):
    result: SearchPassagesResponseBodyTypedDict


class SearchPassagesResponse(BaseModel):
    next: Callable[[], Optional[SearchPassagesResponse]]

    result: SearchPassagesResponseBody
